### ISSUE TITLE
Add Inline Timestamp Functionality

### ISSUE THREAD

**Issue by feldmueller** [KorAP/Krill#132]
For video transcripts in KoKoKom it would be great to have the possibility to display timestamps in the concordances / texts. Possibly in combination with the speaker, e.g. `<5:38-6:08 Mai Thi Nguyen-Kim> Die allermeisten Menschen identifizieren sich...`

**Comment by Akron** [comment]
The annotation now looks like `<p title="06:37 / Marie ">Genau. Wir... </p>`. The mechanism to establish that would reuse the method to show pagebreaks inline. The problem I see is: We currently enforce to show all pagebreaks in snippets (though they are rare), but we probably don't want to enforce all annotations to be visible in such a way. This may either be triggered by a meta data value of the text or a configuration of the instance. For the moment I would go for the latter.

**Comment by feldmueller** [comment]
Annotation now looks like this: `<u who="Mai Thi Nguyen-Kim" start="0:00-0:05">(Räuspern) Wie viele Geschlechter gibt es? Wenn man hierzu öffentliche Diskussionen verfolgt, vergeht einem schnell die Lust.</u>`

**Comment by Akron** [comment]
We agreed that a frontend view like `[end=0:05][start=0:00][who=May Thi Nguyen-Kim]` (alphabetically sorted milestones) is fine for now.

**Comment by Akron** [comment]
There is now a commit proposal (#8605) to make Kalamar configurable regarding the context (so `<u>` can be assumed as default contexts instead auf `<p>`).
