### ISSUE TITLE
SubSpans need to be sorted, when starting with a negative offset

### ISSUE THREAD

**Issue by Akron** [KorAP/Krill#14]
SubSpans need to be sorted, in case the offset is negative, as the ending of embedded spans is not in a defined order.
There is a failing test at `TestSubSpanIndex#testCaseNegativeSubSpan` in the `sort-subspans-bug` branch.

**Comment by margaretha** [comment]
This should have been fixed in 5677b68030323a8df7bfe174b9ce406ca8563385. @Akron: 
Could you please check the test?

**Comment by Akron** [comment]
Yes - was just not closed.
