### ISSUE TITLE
Multiple distances in Cosmas Query

### ISSUE THREAD

**Issue by margaretha** [KorAP/Krill#16]
Multiple distance query needs a synchronization among the distances so that they refer to the same elements/terms.

**Comment by margaretha** [comment]
For the cosmas query: das /+w1:3,s1:1 Buch
"das Buch" in the same sentence is returned as a match.

The real problem might not be the synchronization of same operands.

**Comment by Akron** [comment]
After a round of testing it seems the problem is not reproducible in recent versions of KorAP or the KorAP data. So I guess I will close this issue for now.

**Comment by margaretha** [comment]
Fixed. There was not a problem with multiple distance queries or spans but with skipping in ElementDistanceSpan.
