### ISSUE TITLE
Unordered element distance spans

### ISSUE THREAD

**Issue by margaretha** [KorAP/Krill#26]
The results of of an unordered element distance spans may become unsorted. The current strategy is to create a list of matches for the smallest subspan. When both sub-spans are of the same occurrence, the second subspan is chosen and the first subspan is proceed later. However, there is a possibility that a match for the first subspan has a smaller position than those of the second subspan.

**Comment by Akron** [comment]
I don't really understand the strategy. If I understand the problem correctly, you are refering to the inclusive distance queries of cosmas2, with 3 subspans being part of it. ```<subspan1>``` and ```<subspan2>``` being the anchor with ```<subspanBetween>{0,}``` being the list of subspans in between and surrounding. Does the problem occur, when ```<subspan1>``` equals ```<subspan2>```?

**Comment by margaretha** [comment]
> Does the problem occur, when ```<subspan1>``` equals ```<subspan2>```?
yes when ```<subspan1>``` occurs in the same place of ```<subspan2>```.

I have already fixed this and pushed the commit, but it is not shown in Github.

**Comment by Akron** [comment]
Ah - great. Maybe Gerrit is out-of-sync again?

**Comment by margaretha** [comment]
It seems so. I just check out a new copy from Gerrit and the history is the same as my local history.

**Comment by Akron** [comment]
I get multiple null pointers from master now:
```
  TestMultipleDistanceIndex.testCase1:125 » NullPointer
  TestMultipleDistanceIndex.testCase2:179 » NullPointer
  TestMultipleDistanceIndex.testCase3:211 » NullPointer
  TestMultipleDistanceIndex.testCase4:257 » NullPointer
  TestMultipleDistanceIndex.testCase5:285 » NullPointer
```

**Comment by Akron** [comment]
Sync seems still to be broken.

@kupietz: Can you help?
