### ISSUE TITLE
Optional negated classes do not work properly

### ISSUE THREAD

**Issue by Akron** [KorAP/Krill#29]
Currently a query like ```der {[pos!=ADJA]*} Mann``` throws an error.

Reported by @margaretha

**Comment by Akron** [comment]
This seems to be an index problem with the Wiki instance - the deserialization looks fine.

**Comment by margaretha** [comment]
Hi Nils, you are right, I tested it using the latest index on /kalamar. It works. However one of the results are repeated multiple times:
Call-Center wehren sich gegen Vorwurf Von Cornelia Steiner SAALFELD. Detlef Tiegel heißt der Mann

**Comment by Akron** [comment]
I will test this against the wiki instance. The interpretation of the query is not easy to understand, so there may be a problem in the interpretation leading to identical matches.

**Comment by Akron** [comment]
Seems to work now.
