### ISSUE TITLE
Provide an API to expose index version

### ISSUE THREAD

**Issue by Akron** [KorAP/Krill#62]
Currently, the state of an index is unknown. To see if an index has changed since the last visit (newly introduced, deleted or modified documents), the index may respond with a version code. This can be helpful for caching in clients such as the [RKorAPClient](https://github.com/KorAP/RKorAPClient). To have this feature stable in a distributed environment, it may be enough to return a hash value of arbitrary length instead of an incremental version number.

Once this is implemented, it needs to be served by Kustvakt.

This feature was suggested by @kupietz .

**Comment by kupietz** [comment]
From the API point of view, [statistics](https://github.com/KorAP/Kustvakt/wiki/Service:-Virtual-Corpus-Statistics) could return an informal human readable revision string, leaving it open whether it contains a corpus revision name, a date, a PID, a description or all. 

Clients would have to make their cache hash calculations depend on it  - or invalidate existing caches once this string changes.

**Comment by Akron** [comment]
Realising this using either an ```ETag``` or a ```Last-Modified``` header and in the long run respecting ```If-None-Match``` and ```If-Modified-Since``` seems to be a reasonable approach.

**Comment by Akron** [comment]
https://korap.ids-mannheim.de/gerrit/c/KorAP/Krill/+/2746 addresses this issue and introduces a fingerprint method to KrillIndex. I am open for suggestions about how to make this public. After rethinking, ```ETag``` is probably not a good idea.

**Comment by morckx** [comment]
Maybe we can first simply export the API under an appropriate name.
We could already use it then with RKorAP-Client and have time for thinking about possible HTTP-header integrations.

**Comment by kupietz** [comment]
Maybe we can start with simply exporting the API under an appropriate name. We could then already use it with RKorAPClient and have time for thinking about a http header integration.

**Comment by Akron** [comment]
https://korap.ids-mannheim.de/gerrit/c/KorAP/Kustvakt/+/2752 adds an experimental ```X-Index-Revision``` header to statistics.
