### ISSUE TITLE
SpanFocusQuery() needs to sort spans

### ISSUE THREAD

**Issue by Akron** [KorAP/Krill#7]
Currently spans returned by `focus()` are not guaranteed to be sorted, but a lot of queries rely on that property. There are two cases that are problematic and force the use of forward-looking span caches:

a) The span `<a>...{1:...}...</a>` is modified using `focus(1:...)`. A following span `<a>{1:...}...</a>` has the class 1 in a preceding position.

b) The span `<a>...{1:...}...{2:...}...</a>` is modified using `focus(2:...)`, but still contains a class 1. Now, if the span is again modified using `focus(1:...)` a preceding match span may be `<a>...{2:...}...{1:...}...</a>`, so the second class 1 may precede the first class 1.

There is now a failing test [TestFocusIndex#testFocusSorting in the focus-sort branch](https://github.com/KorAP/Krill/tree/focus-sort).

P.S. This issue refers to #169 in our old Trac ticket system.

**Comment by Akron** [comment]
Rebased and part of master.

**Comment by margaretha** [comment]
This has been implemented. The sorting has to be activated in the SpanFocusQuery by setting isSorted=false. By default, isSorted is true meaning the resulting focusSpans is automatically/naturally sorted.

> focus(2:...), but still contains a class 1.

I wonder if this is necessary since it complicates things. Theoretically, the matches have been reduced to class 2 then, so it should not have class 1 anymore...

**Comment by Akron** [comment]
> This has been implemented.

Can you alter the failing test to make it work, then we can adjust the SpanQueryWrappers accordingly.

> I wonder if this is necessary since it complicates things. 

I guess then we need to strip these classes from the payload. Which is problematic, in case we want to do other things with the classes instead of focussing. Or we don't allow nested unsorted focus queries.

**Comment by margaretha** [comment]
I have fixed the test. It is in gerrit. 

Can I remove the focus-sort branch? I suppose we don't need it anymore.

**Comment by Akron** [comment]
Thank you! Yes, you can remove the focus-sort branch.

I will update the wrapper to use the sorted FocusSpans. I don't think the solution is perfect, as it operates on a fixed window size, so it's easy to create a broken test (that will skip a correct match without a warning for the user), but it's definitely better than no sorting.

**Comment by margaretha** [comment]
yes otherwise, all the matches in a doc has to be collected and sorted.

**Comment by Akron** [comment]
Only in the worst case, I think. The wrapping query is guaranteed to be sorted, so when it moves forward, all spans in the priority queue with start position smaller than the new start position of the wrapping query can be released, I assume. In most real cases this will make the window smaller than 10 (like focussing on the noun in an np).

**Comment by Akron** [comment]
For the very common case of the text being the wrapping query of the focus operation (which is done for right extending queries automatically), I will introduce a special handling, as a Within query is theoretically a "maybeUnsorted" query, but in this case, it is guaranteed to be sorted.

**Comment by Akron** [comment]
Improvement adopted in https://github.com/KorAP/Krill/commit/8c67615a491e4c61e5bbd6d6cfe8d5a5517990e6 .

**Comment by margaretha** [comment]
> The wrapping query is guaranteed to be sorted, so when it moves forward, all spans in the priority queue with start position smaller than the new start position of the wrapping query can be released, I assume.

Thanks for the suggestion! It has been implemented in 8c67615a491e4c61e5bbd6d6cfe8d5a5517990e6.

Focus-sort branch has been removed.

**Comment by Akron** [comment]
The wrapping algorithm for sorting focus spans is now a bit cautious, but should work. A focus query requires sorting when the operand
Subqueries are marked as "maybeUnsorted", in case they are
- relation queries
- within queries (but not match or startswith)
- have relevant "maybeUnsorted" operands

This is also true for subqueries that do not contain any classes, so this should be optimized. There are probably more cases where sorting is not relevant.

**Comment by Akron** [comment]
The wrapping mechanism was added in https://github.com/KorAP/Krill/commit/a26184e949df2e4228d44ac0304659ce6531cbd3 .
